// Hairstyle database — each style is defined by:
//   - metadata: name, gender, compatible hair types, face shape affinity
//   - profile: parametric control points relative to facial landmarks
//     that define the silhouette (crown height, side volume, length, bangs)
//   - harmony: which facial proportion issues this style corrects or worsens
//
// Profile coordinates are offsets from landmark positions, normalized to
// face width (x) and face height (y). Positive x = outward from center,
// positive y = downward.

// Landmark anchors used for positioning:
//   10  = top of forehead (crown reference)
//   234 = left temple,  454 = right temple
//   93  = left ear,     323 = right ear
//   172 = left jaw,     397 = right jaw
//   152 = chin
//   21  = left hairline, 251 = right hairline
//   127 = left cheekbone area, 356 = right cheekbone area

const HAIR_TYPES = ["straight", "wavy", "curly", "coily"];

// Face shape affinity: 1.0 = ideal, 0.5 = neutral, 0.0 = avoid
// Proportion corrections: positive = helps that issue, negative = worsens
const database = {
  // ===================== MEN'S STYLES =====================
  buzzCut: {
    id: "buzzCut",
    name: "Buzz Cut",
    gender: "men",
    hairTypes: ["straight", "wavy", "curly", "coily"],
    faceShapeAffinity: { oval: 1.0, square: 0.9, diamond: 0.7, oblong: 0.4, round: 0.3, heart: 0.5, triangle: 0.6 },
    proportionEffect: { addsHeight: 0, addsWidth: 0, coversForeheadPct: 0, lengthPastChin: 0 },
    harmony: { narrowFace: -0.5, wideFace: 0.3, longForehead: -0.8, shortForehead: 0.8, strongJaw: 0.5, weakChin: -0.3 },
    description: "Closely clipped all over, minimal length. Exposes full face structure — works best on strong, balanced features.",
    profile: {
      crownHeight: 0.02,
      sideVolume: 0.01,
      backLength: 0.02,
      bangDrop: 0,
      bangType: "none",
      lengthLevel: "above-ear",
      taperSides: true,
      textureDetail: "minimal",
    },
  },

  crewCut: {
    id: "crewCut",
    name: "Crew Cut",
    gender: "men",
    hairTypes: ["straight", "wavy", "curly"],
    faceShapeAffinity: { oval: 0.9, square: 0.8, diamond: 0.7, oblong: 0.5, round: 0.6, heart: 0.6, triangle: 0.7 },
    proportionEffect: { addsHeight: 0.05, addsWidth: 0.02, coversForeheadPct: 0.1, lengthPastChin: 0 },
    harmony: { narrowFace: -0.2, wideFace: 0.2, longForehead: -0.3, shortForehead: 0.4, strongJaw: 0.3, weakChin: -0.1 },
    description: "Short on sides, slightly longer on top. Clean and structured — adds minimal height at the crown.",
    profile: {
      crownHeight: 0.06,
      sideVolume: 0.02,
      backLength: 0.03,
      bangDrop: 0.05,
      bangType: "short-textured",
      lengthLevel: "above-ear",
      taperSides: true,
      textureDetail: "light",
    },
  },

  ivyLeague: {
    id: "ivyLeague",
    name: "Ivy League",
    gender: "men",
    hairTypes: ["straight", "wavy"],
    faceShapeAffinity: { oval: 1.0, square: 0.8, diamond: 0.8, oblong: 0.6, round: 0.7, heart: 0.7, triangle: 0.7 },
    proportionEffect: { addsHeight: 0.08, addsWidth: 0.03, coversForeheadPct: 0.15, lengthPastChin: 0 },
    harmony: { narrowFace: -0.1, wideFace: 0.3, longForehead: -0.1, shortForehead: 0.5, strongJaw: 0.2, weakChin: 0 },
    description: "Longer crew cut — enough length on top to part to the side. Polished and versatile.",
    profile: {
      crownHeight: 0.08,
      sideVolume: 0.03,
      backLength: 0.04,
      bangDrop: 0.1,
      bangType: "side-swept-short",
      lengthLevel: "above-ear",
      taperSides: true,
      textureDetail: "light",
    },
  },

  sidePart: {
    id: "sidePart",
    name: "Side Part",
    gender: "men",
    hairTypes: ["straight", "wavy"],
    faceShapeAffinity: { oval: 1.0, round: 0.8, square: 0.7, oblong: 0.6, heart: 0.8, diamond: 0.7, triangle: 0.7 },
    proportionEffect: { addsHeight: 0.1, addsWidth: 0.04, coversForeheadPct: 0.25, lengthPastChin: 0 },
    harmony: { narrowFace: 0, wideFace: 0.2, longForehead: 0.2, shortForehead: 0.3, strongJaw: 0.1, weakChin: 0 },
    description: "Classic part to one side with volume on top. Creates an angular, structured look that balances most face shapes.",
    profile: {
      crownHeight: 0.1,
      sideVolume: 0.04,
      backLength: 0.05,
      bangDrop: 0.15,
      bangType: "side-swept",
      lengthLevel: "ear",
      taperSides: false,
      textureDetail: "moderate",
    },
  },

  combOver: {
    id: "combOver",
    name: "Comb Over",
    gender: "men",
    hairTypes: ["straight", "wavy"],
    faceShapeAffinity: { oval: 0.9, round: 0.8, square: 0.7, oblong: 0.5, heart: 0.7, diamond: 0.7, triangle: 0.6 },
    proportionEffect: { addsHeight: 0.12, addsWidth: 0.05, coversForeheadPct: 0.3, lengthPastChin: 0 },
    harmony: { narrowFace: 0.1, wideFace: 0.3, longForehead: 0.3, shortForehead: 0.2, strongJaw: 0.1, weakChin: 0 },
    description: "Hair swept to one side with a defined part. Adds asymmetric volume on top — good for balancing wider faces.",
    profile: {
      crownHeight: 0.12,
      sideVolume: 0.05,
      backLength: 0.05,
      bangDrop: 0.18,
      bangType: "side-swept",
      lengthLevel: "ear",
      taperSides: true,
      textureDetail: "moderate",
    },
  },

  pompadour: {
    id: "pompadour",
    name: "Pompadour",
    gender: "men",
    hairTypes: ["straight", "wavy"],
    faceShapeAffinity: { oval: 0.9, round: 0.9, square: 0.7, oblong: 0.3, heart: 0.6, diamond: 0.8, triangle: 0.7 },
    proportionEffect: { addsHeight: 0.25, addsWidth: 0.04, coversForeheadPct: 0, lengthPastChin: 0 },
    harmony: { narrowFace: 0.1, wideFace: 0.7, longForehead: -0.5, shortForehead: 0.9, strongJaw: 0, weakChin: 0.1 },
    description: "Voluminous height on top, swept up and back. Dramatically elongates the face — best for round or wide faces.",
    profile: {
      crownHeight: 0.25,
      sideVolume: 0.04,
      backLength: 0.06,
      bangDrop: 0,
      bangType: "none",
      lengthLevel: "ear",
      taperSides: true,
      textureDetail: "moderate",
    },
  },

  quiff: {
    id: "quiff",
    name: "Quiff",
    gender: "men",
    hairTypes: ["straight", "wavy"],
    faceShapeAffinity: { oval: 1.0, round: 0.9, square: 0.8, oblong: 0.4, heart: 0.7, diamond: 0.8, triangle: 0.7 },
    proportionEffect: { addsHeight: 0.2, addsWidth: 0.05, coversForeheadPct: 0.05, lengthPastChin: 0 },
    harmony: { narrowFace: 0.2, wideFace: 0.6, longForehead: -0.3, shortForehead: 0.8, strongJaw: 0.1, weakChin: 0.1 },
    description: "Swept-up volume at the front with textured styling. Adds significant height while keeping a relaxed finish.",
    profile: {
      crownHeight: 0.2,
      sideVolume: 0.05,
      backLength: 0.05,
      bangDrop: 0.03,
      bangType: "lifted",
      lengthLevel: "ear",
      taperSides: true,
      textureDetail: "moderate",
    },
  },

  slickBack: {
    id: "slickBack",
    name: "Slick Back",
    gender: "men",
    hairTypes: ["straight", "wavy"],
    faceShapeAffinity: { oval: 0.9, square: 0.8, diamond: 0.7, oblong: 0.5, round: 0.5, heart: 0.6, triangle: 0.7 },
    proportionEffect: { addsHeight: 0.08, addsWidth: 0, coversForeheadPct: 0, lengthPastChin: 0 },
    harmony: { narrowFace: -0.2, wideFace: 0.2, longForehead: -0.6, shortForehead: 0.5, strongJaw: 0.4, weakChin: -0.2 },
    description: "Hair combed straight back with product. Exposes forehead fully — works best on balanced proportions with a strong jawline.",
    profile: {
      crownHeight: 0.08,
      sideVolume: 0.02,
      backLength: 0.08,
      bangDrop: 0,
      bangType: "none",
      lengthLevel: "ear",
      taperSides: false,
      textureDetail: "smooth",
    },
  },

  texturedCrop: {
    id: "texturedCrop",
    name: "Textured Crop",
    gender: "men",
    hairTypes: ["straight", "wavy", "curly"],
    faceShapeAffinity: { oval: 0.9, round: 0.7, square: 0.8, oblong: 0.7, heart: 0.9, diamond: 0.8, triangle: 0.7 },
    proportionEffect: { addsHeight: 0.06, addsWidth: 0.03, coversForeheadPct: 0.4, lengthPastChin: 0 },
    harmony: { narrowFace: 0.1, wideFace: 0, longForehead: 0.5, shortForehead: -0.2, strongJaw: 0.1, weakChin: 0.1 },
    description: "Short textured top with a forward fringe. The fringe shortens a long forehead while adding casual texture.",
    profile: {
      crownHeight: 0.06,
      sideVolume: 0.03,
      backLength: 0.04,
      bangDrop: 0.2,
      bangType: "textured-fringe",
      lengthLevel: "above-ear",
      taperSides: true,
      textureDetail: "heavy",
    },
  },

  frenchCrop: {
    id: "frenchCrop",
    name: "French Crop",
    gender: "men",
    hairTypes: ["straight", "wavy"],
    faceShapeAffinity: { oval: 0.9, round: 0.6, square: 0.8, oblong: 0.8, heart: 0.9, diamond: 0.7, triangle: 0.7 },
    proportionEffect: { addsHeight: 0.04, addsWidth: 0.02, coversForeheadPct: 0.5, lengthPastChin: 0 },
    harmony: { narrowFace: 0.1, wideFace: -0.1, longForehead: 0.7, shortForehead: -0.5, strongJaw: 0, weakChin: 0 },
    description: "Short all over with a blunt, straight-across fringe. Strongly shortens the forehead — designed for long or oblong faces.",
    profile: {
      crownHeight: 0.04,
      sideVolume: 0.02,
      backLength: 0.03,
      bangDrop: 0.25,
      bangType: "blunt-fringe",
      lengthLevel: "above-ear",
      taperSides: true,
      textureDetail: "light",
    },
  },

  caesarCut: {
    id: "caesarCut",
    name: "Caesar Cut",
    gender: "men",
    hairTypes: ["straight", "wavy", "curly"],
    faceShapeAffinity: { oval: 0.8, round: 0.6, square: 0.8, oblong: 0.7, heart: 0.7, diamond: 0.7, triangle: 0.7 },
    proportionEffect: { addsHeight: 0.03, addsWidth: 0.02, coversForeheadPct: 0.35, lengthPastChin: 0 },
    harmony: { narrowFace: 0, wideFace: 0, longForehead: 0.5, shortForehead: -0.3, strongJaw: 0, weakChin: 0 },
    description: "Short, horizontally styled with a short fringe. Low-maintenance cut that partially covers the forehead.",
    profile: {
      crownHeight: 0.04,
      sideVolume: 0.02,
      backLength: 0.03,
      bangDrop: 0.15,
      bangType: "short-fringe",
      lengthLevel: "above-ear",
      taperSides: false,
      textureDetail: "light",
    },
  },

  undercut: {
    id: "undercut",
    name: "Undercut",
    gender: "men",
    hairTypes: ["straight", "wavy", "curly"],
    faceShapeAffinity: { oval: 0.9, round: 0.8, square: 0.8, oblong: 0.5, heart: 0.7, diamond: 0.9, triangle: 0.6 },
    proportionEffect: { addsHeight: 0.15, addsWidth: -0.03, coversForeheadPct: 0.1, lengthPastChin: 0 },
    harmony: { narrowFace: -0.2, wideFace: 0.6, longForehead: -0.2, shortForehead: 0.6, strongJaw: 0.3, weakChin: 0.1 },
    description: "Disconnected — very short or shaved sides with significant length on top. Creates strong vertical contrast.",
    profile: {
      crownHeight: 0.15,
      sideVolume: 0.01,
      backLength: 0.04,
      bangDrop: 0.1,
      bangType: "variable",
      lengthLevel: "above-ear",
      taperSides: false,
      textureDetail: "moderate",
    },
  },

  lowFade: {
    id: "lowFade",
    name: "Low Fade",
    gender: "men",
    hairTypes: ["straight", "wavy", "curly", "coily"],
    faceShapeAffinity: { oval: 0.9, round: 0.7, square: 0.9, oblong: 0.6, heart: 0.7, diamond: 0.8, triangle: 0.8 },
    proportionEffect: { addsHeight: 0.1, addsWidth: -0.02, coversForeheadPct: 0.1, lengthPastChin: 0 },
    harmony: { narrowFace: -0.1, wideFace: 0.4, longForehead: -0.1, shortForehead: 0.4, strongJaw: 0.3, weakChin: 0.1 },
    description: "Gradual taper starting just above the ear. Keeps structure at the sides while adding height on top.",
    profile: {
      crownHeight: 0.1,
      sideVolume: 0.02,
      backLength: 0.04,
      bangDrop: 0.08,
      bangType: "variable",
      lengthLevel: "ear",
      taperSides: true,
      textureDetail: "moderate",
    },
  },

  midFade: {
    id: "midFade",
    name: "Mid Fade",
    gender: "men",
    hairTypes: ["straight", "wavy", "curly", "coily"],
    faceShapeAffinity: { oval: 0.9, round: 0.8, square: 0.8, oblong: 0.5, heart: 0.7, diamond: 0.8, triangle: 0.7 },
    proportionEffect: { addsHeight: 0.12, addsWidth: -0.04, coversForeheadPct: 0.1, lengthPastChin: 0 },
    harmony: { narrowFace: -0.2, wideFace: 0.5, longForehead: -0.1, shortForehead: 0.5, strongJaw: 0.2, weakChin: 0.1 },
    description: "Fade starting at the temple level. More contrast than a low fade — narrows the sides noticeably.",
    profile: {
      crownHeight: 0.12,
      sideVolume: 0.01,
      backLength: 0.04,
      bangDrop: 0.08,
      bangType: "variable",
      lengthLevel: "above-ear",
      taperSides: true,
      textureDetail: "moderate",
    },
  },

  highFade: {
    id: "highFade",
    name: "High Fade",
    gender: "men",
    hairTypes: ["straight", "wavy", "curly", "coily"],
    faceShapeAffinity: { oval: 0.8, round: 0.9, square: 0.7, oblong: 0.4, heart: 0.6, diamond: 0.8, triangle: 0.6 },
    proportionEffect: { addsHeight: 0.15, addsWidth: -0.06, coversForeheadPct: 0.05, lengthPastChin: 0 },
    harmony: { narrowFace: -0.4, wideFace: 0.7, longForehead: -0.2, shortForehead: 0.6, strongJaw: 0.2, weakChin: 0 },
    description: "Fade starting well above the temple. Maximum side reduction — strongly elongates the face.",
    profile: {
      crownHeight: 0.15,
      sideVolume: 0.005,
      backLength: 0.03,
      bangDrop: 0.05,
      bangType: "variable",
      lengthLevel: "above-ear",
      taperSides: true,
      textureDetail: "moderate",
    },
  },

  taper: {
    id: "taper",
    name: "Taper",
    gender: "men",
    hairTypes: ["straight", "wavy", "curly", "coily"],
    faceShapeAffinity: { oval: 1.0, round: 0.7, square: 0.8, oblong: 0.7, heart: 0.8, diamond: 0.7, triangle: 0.8 },
    proportionEffect: { addsHeight: 0.08, addsWidth: 0.01, coversForeheadPct: 0.1, lengthPastChin: 0 },
    harmony: { narrowFace: 0, wideFace: 0.2, longForehead: 0, shortForehead: 0.3, strongJaw: 0.2, weakChin: 0 },
    description: "Gradual length reduction toward the neckline. Classic, natural shape that works with most face structures.",
    profile: {
      crownHeight: 0.08,
      sideVolume: 0.03,
      backLength: 0.05,
      bangDrop: 0.1,
      bangType: "side-swept-short",
      lengthLevel: "ear",
      taperSides: true,
      textureDetail: "light",
    },
  },

  manBun: {
    id: "manBun",
    name: "Man Bun",
    gender: "men",
    hairTypes: ["straight", "wavy", "curly"],
    faceShapeAffinity: { oval: 0.8, round: 0.6, square: 0.7, oblong: 0.5, heart: 0.7, diamond: 0.8, triangle: 0.6 },
    proportionEffect: { addsHeight: 0.2, addsWidth: -0.02, coversForeheadPct: 0, lengthPastChin: 0 },
    harmony: { narrowFace: -0.3, wideFace: 0.4, longForehead: -0.7, shortForehead: 0.6, strongJaw: 0.4, weakChin: -0.3 },
    description: "Long hair gathered into a bun at the crown or back. Fully exposes the face — requires balanced features.",
    profile: {
      crownHeight: 0.2,
      sideVolume: 0.01,
      backLength: 0.1,
      bangDrop: 0,
      bangType: "none",
      lengthLevel: "pulled-up",
      taperSides: false,
      textureDetail: "minimal",
    },
  },

  topKnot: {
    id: "topKnot",
    name: "Top Knot",
    gender: "men",
    hairTypes: ["straight", "wavy", "curly"],
    faceShapeAffinity: { oval: 0.8, round: 0.7, square: 0.7, oblong: 0.3, heart: 0.6, diamond: 0.7, triangle: 0.5 },
    proportionEffect: { addsHeight: 0.25, addsWidth: -0.04, coversForeheadPct: 0, lengthPastChin: 0 },
    harmony: { narrowFace: -0.4, wideFace: 0.6, longForehead: -0.7, shortForehead: 0.7, strongJaw: 0.3, weakChin: -0.2 },
    description: "Hair tied at the very top of the head, often with shaved or faded sides. Maximum vertical addition.",
    profile: {
      crownHeight: 0.25,
      sideVolume: 0.005,
      backLength: 0.03,
      bangDrop: 0,
      bangType: "none",
      lengthLevel: "pulled-up",
      taperSides: true,
      textureDetail: "minimal",
    },
  },

  curtainHair: {
    id: "curtainHair",
    name: "Curtain Hair",
    gender: "men",
    hairTypes: ["straight", "wavy"],
    faceShapeAffinity: { oval: 0.9, round: 0.7, square: 0.8, oblong: 0.7, heart: 0.9, diamond: 0.7, triangle: 0.7 },
    proportionEffect: { addsHeight: 0.05, addsWidth: 0.06, coversForeheadPct: 0.5, lengthPastChin: 0 },
    harmony: { narrowFace: 0.3, wideFace: -0.2, longForehead: 0.6, shortForehead: -0.4, strongJaw: 0, weakChin: 0 },
    description: "Center-parted with hair falling to each side of the forehead. Adds width at the temples and covers the forehead edges.",
    profile: {
      crownHeight: 0.05,
      sideVolume: 0.06,
      backLength: 0.06,
      bangDrop: 0.3,
      bangType: "curtain",
      lengthLevel: "ear",
      taperSides: false,
      textureDetail: "moderate",
    },
  },

  shagMen: {
    id: "shagMen",
    name: "Shag",
    gender: "men",
    hairTypes: ["straight", "wavy", "curly"],
    faceShapeAffinity: { oval: 0.8, round: 0.6, square: 0.7, oblong: 0.8, heart: 0.8, diamond: 0.8, triangle: 0.7 },
    proportionEffect: { addsHeight: 0.06, addsWidth: 0.08, coversForeheadPct: 0.4, lengthPastChin: 0 },
    harmony: { narrowFace: 0.5, wideFace: -0.3, longForehead: 0.4, shortForehead: -0.2, strongJaw: -0.1, weakChin: 0.1 },
    description: "Layered, textured cut with volume throughout. Adds significant side width — best for narrow or oblong faces.",
    profile: {
      crownHeight: 0.08,
      sideVolume: 0.1,
      backLength: 0.1,
      bangDrop: 0.2,
      bangType: "textured-fringe",
      lengthLevel: "below-ear",
      taperSides: false,
      textureDetail: "heavy",
    },
  },

  mullet: {
    id: "mullet",
    name: "Modern Mullet",
    gender: "men",
    hairTypes: ["straight", "wavy", "curly"],
    faceShapeAffinity: { oval: 0.7, round: 0.5, square: 0.7, oblong: 0.6, heart: 0.7, diamond: 0.8, triangle: 0.5 },
    proportionEffect: { addsHeight: 0.08, addsWidth: 0.04, coversForeheadPct: 0.2, lengthPastChin: 0.3 },
    harmony: { narrowFace: 0.2, wideFace: 0, longForehead: 0.2, shortForehead: 0.1, strongJaw: 0, weakChin: 0.2 },
    description: "Short-to-medium on top and sides, longer in the back. The back length extends the visual face downward.",
    profile: {
      crownHeight: 0.08,
      sideVolume: 0.04,
      backLength: 0.25,
      bangDrop: 0.12,
      bangType: "textured-fringe",
      lengthLevel: "below-ear",
      taperSides: false,
      textureDetail: "moderate",
    },
  },

  mohawk: {
    id: "mohawk",
    name: "Mohawk",
    gender: "men",
    hairTypes: ["straight", "wavy", "curly", "coily"],
    faceShapeAffinity: { oval: 0.7, round: 0.8, square: 0.6, oblong: 0.3, heart: 0.5, diamond: 0.7, triangle: 0.5 },
    proportionEffect: { addsHeight: 0.3, addsWidth: -0.08, coversForeheadPct: 0, lengthPastChin: 0 },
    harmony: { narrowFace: -0.6, wideFace: 0.8, longForehead: -0.4, shortForehead: 0.7, strongJaw: 0, weakChin: 0 },
    description: "Strip of hair down the center, sides shaved. Extreme vertical elongation — only for round or very wide faces.",
    profile: {
      crownHeight: 0.3,
      sideVolume: 0,
      backLength: 0.05,
      bangDrop: 0,
      bangType: "none",
      lengthLevel: "shaved-sides",
      taperSides: false,
      textureDetail: "heavy",
    },
  },

  fauxHawk: {
    id: "fauxHawk",
    name: "Faux Hawk",
    gender: "men",
    hairTypes: ["straight", "wavy", "curly"],
    faceShapeAffinity: { oval: 0.9, round: 0.9, square: 0.7, oblong: 0.4, heart: 0.6, diamond: 0.8, triangle: 0.6 },
    proportionEffect: { addsHeight: 0.18, addsWidth: -0.03, coversForeheadPct: 0.05, lengthPastChin: 0 },
    harmony: { narrowFace: -0.3, wideFace: 0.6, longForehead: -0.3, shortForehead: 0.6, strongJaw: 0.1, weakChin: 0 },
    description: "Softer mohawk — sides are short but not shaved, center is styled upward. Strong height with less commitment.",
    profile: {
      crownHeight: 0.18,
      sideVolume: 0.02,
      backLength: 0.04,
      bangDrop: 0.03,
      bangType: "lifted",
      lengthLevel: "above-ear",
      taperSides: true,
      textureDetail: "moderate",
    },
  },

  spikyHair: {
    id: "spikyHair",
    name: "Spiky",
    gender: "men",
    hairTypes: ["straight", "wavy"],
    faceShapeAffinity: { oval: 0.7, round: 0.8, square: 0.6, oblong: 0.4, heart: 0.6, diamond: 0.7, triangle: 0.6 },
    proportionEffect: { addsHeight: 0.15, addsWidth: 0.03, coversForeheadPct: 0, lengthPastChin: 0 },
    harmony: { narrowFace: -0.1, wideFace: 0.4, longForehead: -0.3, shortForehead: 0.5, strongJaw: 0, weakChin: 0 },
    description: "Hair spiked upward with product. Adds height and texture — casual, youthful look.",
    profile: {
      crownHeight: 0.15,
      sideVolume: 0.03,
      backLength: 0.04,
      bangDrop: 0,
      bangType: "none",
      lengthLevel: "above-ear",
      taperSides: true,
      textureDetail: "heavy",
    },
  },

  messyTextured: {
    id: "messyTextured",
    name: "Messy Textured",
    gender: "men",
    hairTypes: ["straight", "wavy", "curly"],
    faceShapeAffinity: { oval: 0.9, round: 0.7, square: 0.7, oblong: 0.7, heart: 0.8, diamond: 0.8, triangle: 0.7 },
    proportionEffect: { addsHeight: 0.1, addsWidth: 0.06, coversForeheadPct: 0.3, lengthPastChin: 0 },
    harmony: { narrowFace: 0.3, wideFace: -0.1, longForehead: 0.3, shortForehead: 0, strongJaw: 0, weakChin: 0.1 },
    description: "Medium length with intentionally tousled texture. Adds both height and width — a versatile, balanced option.",
    profile: {
      crownHeight: 0.1,
      sideVolume: 0.06,
      backLength: 0.06,
      bangDrop: 0.15,
      bangType: "textured-fringe",
      lengthLevel: "ear",
      taperSides: false,
      textureDetail: "heavy",
    },
  },

  afroMen: {
    id: "afroMen",
    name: "Afro",
    gender: "men",
    hairTypes: ["curly", "coily"],
    faceShapeAffinity: { oval: 0.8, round: 0.5, square: 0.7, oblong: 0.6, heart: 0.7, diamond: 0.8, triangle: 0.6 },
    proportionEffect: { addsHeight: 0.2, addsWidth: 0.15, coversForeheadPct: 0.2, lengthPastChin: 0 },
    harmony: { narrowFace: 0.6, wideFace: -0.4, longForehead: 0.1, shortForehead: 0.3, strongJaw: -0.2, weakChin: 0.1 },
    description: "Natural curly/coily texture grown out into a rounded shape. Adds substantial width and height — great for narrow faces.",
    profile: {
      crownHeight: 0.2,
      sideVolume: 0.15,
      backLength: 0.15,
      bangDrop: 0.1,
      bangType: "natural",
      lengthLevel: "above-ear",
      taperSides: false,
      textureDetail: "heavy",
    },
  },

  flatTop: {
    id: "flatTop",
    name: "Flat Top",
    gender: "men",
    hairTypes: ["curly", "coily"],
    faceShapeAffinity: { oval: 0.7, round: 0.8, square: 0.5, oblong: 0.4, heart: 0.6, diamond: 0.7, triangle: 0.6 },
    proportionEffect: { addsHeight: 0.2, addsWidth: 0, coversForeheadPct: 0, lengthPastChin: 0 },
    harmony: { narrowFace: -0.2, wideFace: 0.5, longForehead: -0.3, shortForehead: 0.6, strongJaw: 0.1, weakChin: 0 },
    description: "Flat, level top with faded or tapered sides. Adds height without width — a structured, geometric look.",
    profile: {
      crownHeight: 0.2,
      sideVolume: 0.01,
      backLength: 0.04,
      bangDrop: 0,
      bangType: "none",
      lengthLevel: "above-ear",
      taperSides: true,
      textureDetail: "minimal",
    },
  },

  bowlCut: {
    id: "bowlCut",
    name: "Bowl Cut",
    gender: "men",
    hairTypes: ["straight", "wavy"],
    faceShapeAffinity: { oval: 0.6, round: 0.3, square: 0.5, oblong: 0.7, heart: 0.6, diamond: 0.5, triangle: 0.7 },
    proportionEffect: { addsHeight: 0.02, addsWidth: 0.06, coversForeheadPct: 0.8, lengthPastChin: 0 },
    harmony: { narrowFace: 0.3, wideFace: -0.4, longForehead: 0.8, shortForehead: -0.7, strongJaw: -0.1, weakChin: 0 },
    description: "Even length all around with a full fringe. Heavy forehead coverage — only for long foreheads or oblong faces.",
    profile: {
      crownHeight: 0.03,
      sideVolume: 0.06,
      backLength: 0.06,
      bangDrop: 0.35,
      bangType: "blunt-fringe",
      lengthLevel: "ear",
      taperSides: false,
      textureDetail: "smooth",
    },
  },

  longLayersMen: {
    id: "longLayersMen",
    name: "Long Layers",
    gender: "men",
    hairTypes: ["straight", "wavy", "curly"],
    faceShapeAffinity: { oval: 0.8, round: 0.5, square: 0.7, oblong: 0.7, heart: 0.7, diamond: 0.8, triangle: 0.6 },
    proportionEffect: { addsHeight: 0.05, addsWidth: 0.1, coversForeheadPct: 0.3, lengthPastChin: 0.4 },
    harmony: { narrowFace: 0.5, wideFace: -0.3, longForehead: 0.3, shortForehead: -0.1, strongJaw: -0.2, weakChin: 0.3 },
    description: "Shoulder-length or longer with layered movement. Adds width through the mid-face and extends past the chin.",
    profile: {
      crownHeight: 0.05,
      sideVolume: 0.1,
      backLength: 0.35,
      bangDrop: 0.15,
      bangType: "side-swept",
      lengthLevel: "shoulder",
      taperSides: false,
      textureDetail: "moderate",
    },
  },

  mediumLayersMen: {
    id: "mediumLayersMen",
    name: "Medium Layers",
    gender: "men",
    hairTypes: ["straight", "wavy", "curly"],
    faceShapeAffinity: { oval: 0.9, round: 0.6, square: 0.7, oblong: 0.8, heart: 0.8, diamond: 0.8, triangle: 0.7 },
    proportionEffect: { addsHeight: 0.06, addsWidth: 0.07, coversForeheadPct: 0.25, lengthPastChin: 0.1 },
    harmony: { narrowFace: 0.4, wideFace: -0.2, longForehead: 0.3, shortForehead: -0.1, strongJaw: -0.1, weakChin: 0.2 },
    description: "Ear-to-chin length with layers for movement. Balanced volume addition — works with most structures.",
    profile: {
      crownHeight: 0.06,
      sideVolume: 0.07,
      backLength: 0.15,
      bangDrop: 0.12,
      bangType: "side-swept",
      lengthLevel: "below-ear",
      taperSides: false,
      textureDetail: "moderate",
    },
  },

  // ===================== WOMEN'S STYLES =====================
  pixieCut: {
    id: "pixieCut",
    name: "Pixie Cut",
    gender: "women",
    hairTypes: ["straight", "wavy", "curly"],
    faceShapeAffinity: { oval: 1.0, heart: 0.8, diamond: 0.7, square: 0.6, round: 0.5, oblong: 0.6, triangle: 0.6 },
    proportionEffect: { addsHeight: 0.06, addsWidth: 0.02, coversForeheadPct: 0.2, lengthPastChin: 0 },
    harmony: { narrowFace: 0, wideFace: 0.2, longForehead: 0.1, shortForehead: 0.2, strongJaw: 0.2, weakChin: -0.1 },
    description: "Very short, cropped close to the head with some length on top. Exposes face structure — works best on balanced features.",
    profile: {
      crownHeight: 0.06,
      sideVolume: 0.02,
      backLength: 0.03,
      bangDrop: 0.1,
      bangType: "side-swept-short",
      lengthLevel: "above-ear",
      taperSides: true,
      textureDetail: "light",
    },
  },

  longPixie: {
    id: "longPixie",
    name: "Long Pixie",
    gender: "women",
    hairTypes: ["straight", "wavy", "curly"],
    faceShapeAffinity: { oval: 1.0, heart: 0.9, diamond: 0.8, square: 0.7, round: 0.6, oblong: 0.7, triangle: 0.7 },
    proportionEffect: { addsHeight: 0.07, addsWidth: 0.04, coversForeheadPct: 0.35, lengthPastChin: 0 },
    harmony: { narrowFace: 0.1, wideFace: 0.1, longForehead: 0.4, shortForehead: 0, strongJaw: 0.1, weakChin: 0 },
    description: "Pixie with more length on top — enough for a side sweep or textured fringe. More versatile than a standard pixie.",
    profile: {
      crownHeight: 0.07,
      sideVolume: 0.04,
      backLength: 0.04,
      bangDrop: 0.2,
      bangType: "side-swept",
      lengthLevel: "ear",
      taperSides: true,
      textureDetail: "moderate",
    },
  },

  bluntBob: {
    id: "bluntBob",
    name: "Blunt Bob",
    gender: "women",
    hairTypes: ["straight", "wavy"],
    faceShapeAffinity: { oval: 0.9, heart: 0.7, diamond: 0.6, square: 0.5, round: 0.4, oblong: 0.8, triangle: 0.8 },
    proportionEffect: { addsHeight: 0.03, addsWidth: 0.06, coversForeheadPct: 0.1, lengthPastChin: 0 },
    harmony: { narrowFace: 0.4, wideFace: -0.3, longForehead: 0, shortForehead: 0, strongJaw: -0.2, weakChin: 0.3 },
    description: "One-length bob at chin or jaw level. Creates a strong horizontal line — adds width and frames the jaw.",
    profile: {
      crownHeight: 0.03,
      sideVolume: 0.06,
      backLength: 0.08,
      bangDrop: 0.05,
      bangType: "none",
      lengthLevel: "chin",
      taperSides: false,
      textureDetail: "smooth",
    },
  },

  angledBob: {
    id: "angledBob",
    name: "Angled Bob",
    gender: "women",
    hairTypes: ["straight", "wavy"],
    faceShapeAffinity: { oval: 0.9, heart: 0.8, diamond: 0.7, square: 0.7, round: 0.7, oblong: 0.7, triangle: 0.8 },
    proportionEffect: { addsHeight: 0.03, addsWidth: 0.05, coversForeheadPct: 0.1, lengthPastChin: 0.05 },
    harmony: { narrowFace: 0.3, wideFace: -0.1, longForehead: 0, shortForehead: 0, strongJaw: 0.1, weakChin: 0.2 },
    description: "Shorter in the back, longer in the front. The angle creates a slimming diagonal line along the jaw.",
    profile: {
      crownHeight: 0.04,
      sideVolume: 0.05,
      backLength: 0.05,
      bangDrop: 0.06,
      bangType: "none",
      lengthLevel: "chin",
      taperSides: false,
      textureDetail: "smooth",
    },
  },

  layeredBob: {
    id: "layeredBob",
    name: "Layered Bob",
    gender: "women",
    hairTypes: ["straight", "wavy", "curly"],
    faceShapeAffinity: { oval: 0.9, heart: 0.8, diamond: 0.8, square: 0.7, round: 0.6, oblong: 0.8, triangle: 0.8 },
    proportionEffect: { addsHeight: 0.04, addsWidth: 0.07, coversForeheadPct: 0.15, lengthPastChin: 0 },
    harmony: { narrowFace: 0.4, wideFace: -0.2, longForehead: 0.1, shortForehead: 0, strongJaw: 0, weakChin: 0.2 },
    description: "Bob with internal layers for movement and volume. More body than a blunt bob — softens angular features.",
    profile: {
      crownHeight: 0.05,
      sideVolume: 0.08,
      backLength: 0.07,
      bangDrop: 0.08,
      bangType: "side-swept-short",
      lengthLevel: "chin",
      taperSides: false,
      textureDetail: "moderate",
    },
  },

  aLineBob: {
    id: "aLineBob",
    name: "A-Line Bob",
    gender: "women",
    hairTypes: ["straight", "wavy"],
    faceShapeAffinity: { oval: 0.9, heart: 0.7, diamond: 0.7, square: 0.6, round: 0.6, oblong: 0.8, triangle: 0.9 },
    proportionEffect: { addsHeight: 0.02, addsWidth: 0.05, coversForeheadPct: 0.05, lengthPastChin: 0.05 },
    harmony: { narrowFace: 0.3, wideFace: -0.2, longForehead: 0, shortForehead: 0, strongJaw: 0.1, weakChin: 0.3 },
    description: "Stacked shorter in back, gradually longer toward the front. Creates a clean, angular silhouette.",
    profile: {
      crownHeight: 0.03,
      sideVolume: 0.05,
      backLength: 0.04,
      bangDrop: 0.03,
      bangType: "none",
      lengthLevel: "chin",
      taperSides: false,
      textureDetail: "smooth",
    },
  },

  lob: {
    id: "lob",
    name: "Lob (Long Bob)",
    gender: "women",
    hairTypes: ["straight", "wavy", "curly"],
    faceShapeAffinity: { oval: 1.0, heart: 0.8, diamond: 0.8, square: 0.7, round: 0.7, oblong: 0.7, triangle: 0.8 },
    proportionEffect: { addsHeight: 0.03, addsWidth: 0.06, coversForeheadPct: 0.1, lengthPastChin: 0.15 },
    harmony: { narrowFace: 0.3, wideFace: -0.1, longForehead: 0, shortForehead: 0, strongJaw: 0.1, weakChin: 0.3 },
    description: "Bob that falls between chin and shoulder. Extremely versatile length that works with most face shapes.",
    profile: {
      crownHeight: 0.03,
      sideVolume: 0.06,
      backLength: 0.12,
      bangDrop: 0.06,
      bangType: "none",
      lengthLevel: "shoulder",
      taperSides: false,
      textureDetail: "moderate",
    },
  },

  shoulderLayers: {
    id: "shoulderLayers",
    name: "Shoulder-Length Layers",
    gender: "women",
    hairTypes: ["straight", "wavy", "curly"],
    faceShapeAffinity: { oval: 1.0, heart: 0.8, diamond: 0.8, square: 0.8, round: 0.7, oblong: 0.7, triangle: 0.8 },
    proportionEffect: { addsHeight: 0.03, addsWidth: 0.07, coversForeheadPct: 0.15, lengthPastChin: 0.2 },
    harmony: { narrowFace: 0.4, wideFace: -0.1, longForehead: 0.1, shortForehead: 0, strongJaw: 0.1, weakChin: 0.2 },
    description: "Shoulder-length with face-framing layers. The layers add movement and width at the cheekbone level.",
    profile: {
      crownHeight: 0.04,
      sideVolume: 0.07,
      backLength: 0.18,
      bangDrop: 0.08,
      bangType: "face-framing",
      lengthLevel: "shoulder",
      taperSides: false,
      textureDetail: "moderate",
    },
  },

  longLayers: {
    id: "longLayers",
    name: "Long Layers",
    gender: "women",
    hairTypes: ["straight", "wavy", "curly"],
    faceShapeAffinity: { oval: 0.9, heart: 0.7, diamond: 0.8, square: 0.8, round: 0.8, oblong: 0.6, triangle: 0.7 },
    proportionEffect: { addsHeight: 0.02, addsWidth: 0.06, coversForeheadPct: 0.1, lengthPastChin: 0.4 },
    harmony: { narrowFace: 0.3, wideFace: -0.1, longForehead: 0, shortForehead: 0, strongJaw: 0.2, weakChin: 0.3 },
    description: "Long hair with graduated layers starting at the chin or collarbone. Adds movement without sacrificing length.",
    profile: {
      crownHeight: 0.03,
      sideVolume: 0.06,
      backLength: 0.4,
      bangDrop: 0.05,
      bangType: "face-framing",
      lengthLevel: "chest",
      taperSides: false,
      textureDetail: "moderate",
    },
  },

  bluntLong: {
    id: "bluntLong",
    name: "Blunt Long",
    gender: "women",
    hairTypes: ["straight"],
    faceShapeAffinity: { oval: 0.8, heart: 0.6, diamond: 0.7, square: 0.7, round: 0.7, oblong: 0.5, triangle: 0.7 },
    proportionEffect: { addsHeight: 0.01, addsWidth: 0.04, coversForeheadPct: 0.05, lengthPastChin: 0.5 },
    harmony: { narrowFace: 0.2, wideFace: 0, longForehead: 0, shortForehead: 0, strongJaw: 0.2, weakChin: 0.2 },
    description: "One-length long hair with no layers. Clean, sleek look — the weight keeps hair flat and elongating.",
    profile: {
      crownHeight: 0.02,
      sideVolume: 0.04,
      backLength: 0.45,
      bangDrop: 0,
      bangType: "none",
      lengthLevel: "chest",
      taperSides: false,
      textureDetail: "smooth",
    },
  },

  curtainBangs: {
    id: "curtainBangs",
    name: "Curtain Bangs + Long",
    gender: "women",
    hairTypes: ["straight", "wavy"],
    faceShapeAffinity: { oval: 1.0, heart: 0.9, diamond: 0.7, square: 0.7, round: 0.6, oblong: 0.8, triangle: 0.7 },
    proportionEffect: { addsHeight: 0.02, addsWidth: 0.06, coversForeheadPct: 0.5, lengthPastChin: 0.4 },
    harmony: { narrowFace: 0.3, wideFace: -0.2, longForehead: 0.7, shortForehead: -0.4, strongJaw: 0.1, weakChin: 0.2 },
    description: "Long hair with center-parted bangs that frame the face. The bangs cover the outer forehead and blend into layers.",
    profile: {
      crownHeight: 0.03,
      sideVolume: 0.06,
      backLength: 0.4,
      bangDrop: 0.3,
      bangType: "curtain",
      lengthLevel: "chest",
      taperSides: false,
      textureDetail: "moderate",
    },
  },

  sideSweptBangs: {
    id: "sideSweptBangs",
    name: "Side-Swept Bangs + Long",
    gender: "women",
    hairTypes: ["straight", "wavy"],
    faceShapeAffinity: { oval: 0.9, heart: 0.9, diamond: 0.7, square: 0.7, round: 0.7, oblong: 0.7, triangle: 0.7 },
    proportionEffect: { addsHeight: 0.02, addsWidth: 0.05, coversForeheadPct: 0.4, lengthPastChin: 0.4 },
    harmony: { narrowFace: 0.2, wideFace: -0.1, longForehead: 0.5, shortForehead: -0.3, strongJaw: 0.1, weakChin: 0.2 },
    description: "Long hair with bangs swept diagonally across the forehead. Creates an asymmetric line that covers part of the forehead.",
    profile: {
      crownHeight: 0.03,
      sideVolume: 0.05,
      backLength: 0.4,
      bangDrop: 0.25,
      bangType: "side-swept",
      lengthLevel: "chest",
      taperSides: false,
      textureDetail: "moderate",
    },
  },

  fullBangs: {
    id: "fullBangs",
    name: "Full Bangs + Long",
    gender: "women",
    hairTypes: ["straight", "wavy"],
    faceShapeAffinity: { oval: 0.8, heart: 0.9, diamond: 0.6, square: 0.6, round: 0.3, oblong: 0.9, triangle: 0.6 },
    proportionEffect: { addsHeight: 0, addsWidth: 0.04, coversForeheadPct: 0.9, lengthPastChin: 0.4 },
    harmony: { narrowFace: 0.2, wideFace: -0.3, longForehead: 0.9, shortForehead: -0.8, strongJaw: 0, weakChin: 0.2 },
    description: "Straight-across bangs covering the forehead with long hair. Maximum forehead coverage — best for long or high foreheads.",
    profile: {
      crownHeight: 0.02,
      sideVolume: 0.04,
      backLength: 0.4,
      bangDrop: 0.35,
      bangType: "blunt-fringe",
      lengthLevel: "chest",
      taperSides: false,
      textureDetail: "smooth",
    },
  },

  shagWomen: {
    id: "shagWomen",
    name: "Shag",
    gender: "women",
    hairTypes: ["straight", "wavy", "curly"],
    faceShapeAffinity: { oval: 0.9, heart: 0.8, diamond: 0.8, square: 0.7, round: 0.5, oblong: 0.8, triangle: 0.7 },
    proportionEffect: { addsHeight: 0.05, addsWidth: 0.1, coversForeheadPct: 0.5, lengthPastChin: 0.15 },
    harmony: { narrowFace: 0.6, wideFace: -0.3, longForehead: 0.5, shortForehead: -0.2, strongJaw: 0, weakChin: 0.1 },
    description: "Heavily layered with a curtain bang and lots of texture. Maximum volume and width — great for narrow faces.",
    profile: {
      crownHeight: 0.06,
      sideVolume: 0.12,
      backLength: 0.2,
      bangDrop: 0.25,
      bangType: "curtain",
      lengthLevel: "shoulder",
      taperSides: false,
      textureDetail: "heavy",
    },
  },

  wolfCut: {
    id: "wolfCut",
    name: "Wolf Cut",
    gender: "women",
    hairTypes: ["straight", "wavy", "curly"],
    faceShapeAffinity: { oval: 0.8, heart: 0.8, diamond: 0.8, square: 0.7, round: 0.5, oblong: 0.8, triangle: 0.7 },
    proportionEffect: { addsHeight: 0.06, addsWidth: 0.1, coversForeheadPct: 0.5, lengthPastChin: 0.2 },
    harmony: { narrowFace: 0.5, wideFace: -0.3, longForehead: 0.4, shortForehead: -0.2, strongJaw: 0, weakChin: 0.1 },
    description: "Mullet-shag hybrid with heavy layers and a fringe. Combines volume through the crown with length in the back.",
    profile: {
      crownHeight: 0.07,
      sideVolume: 0.1,
      backLength: 0.25,
      bangDrop: 0.25,
      bangType: "curtain",
      lengthLevel: "shoulder",
      taperSides: false,
      textureDetail: "heavy",
    },
  },

  butterflyCut: {
    id: "butterflyCut",
    name: "Butterfly Cut",
    gender: "women",
    hairTypes: ["straight", "wavy"],
    faceShapeAffinity: { oval: 0.9, heart: 0.8, diamond: 0.8, square: 0.8, round: 0.7, oblong: 0.7, triangle: 0.8 },
    proportionEffect: { addsHeight: 0.04, addsWidth: 0.08, coversForeheadPct: 0.3, lengthPastChin: 0.3 },
    harmony: { narrowFace: 0.4, wideFace: -0.1, longForehead: 0.3, shortForehead: 0, strongJaw: 0.2, weakChin: 0.2 },
    description: "Long layers with dramatic face-framing that flips outward at the cheekbone. Creates a fluttery, voluminous silhouette.",
    profile: {
      crownHeight: 0.04,
      sideVolume: 0.08,
      backLength: 0.35,
      bangDrop: 0.15,
      bangType: "face-framing",
      lengthLevel: "chest",
      taperSides: false,
      textureDetail: "moderate",
    },
  },

  faceFramingLayers: {
    id: "faceFramingLayers",
    name: "Face-Framing Layers",
    gender: "women",
    hairTypes: ["straight", "wavy", "curly"],
    faceShapeAffinity: { oval: 1.0, heart: 0.8, diamond: 0.7, square: 0.8, round: 0.7, oblong: 0.7, triangle: 0.8 },
    proportionEffect: { addsHeight: 0.02, addsWidth: 0.06, coversForeheadPct: 0.2, lengthPastChin: 0.35 },
    harmony: { narrowFace: 0.3, wideFace: -0.1, longForehead: 0.2, shortForehead: 0, strongJaw: 0.2, weakChin: 0.2 },
    description: "Long hair with shorter pieces framing the face from the cheekbone down. Softens angular features and adds dimension.",
    profile: {
      crownHeight: 0.03,
      sideVolume: 0.06,
      backLength: 0.38,
      bangDrop: 0.1,
      bangType: "face-framing",
      lengthLevel: "chest",
      taperSides: false,
      textureDetail: "moderate",
    },
  },

  longStraight: {
    id: "longStraight",
    name: "Long Straight",
    gender: "women",
    hairTypes: ["straight"],
    faceShapeAffinity: { oval: 0.8, heart: 0.6, diamond: 0.7, square: 0.7, round: 0.8, oblong: 0.4, triangle: 0.7 },
    proportionEffect: { addsHeight: 0, addsWidth: 0.03, coversForeheadPct: 0, lengthPastChin: 0.5 },
    harmony: { narrowFace: 0.1, wideFace: 0, longForehead: -0.1, shortForehead: 0, strongJaw: 0.3, weakChin: 0.1 },
    description: "Long, sleek hair with no bangs. Draws vertical lines downward — elongates and slims the face overall.",
    profile: {
      crownHeight: 0.02,
      sideVolume: 0.03,
      backLength: 0.45,
      bangDrop: 0,
      bangType: "none",
      lengthLevel: "chest",
      taperSides: false,
      textureDetail: "smooth",
    },
  },

  beachWaves: {
    id: "beachWaves",
    name: "Beach Waves",
    gender: "women",
    hairTypes: ["wavy", "straight"],
    faceShapeAffinity: { oval: 0.9, heart: 0.8, diamond: 0.8, square: 0.8, round: 0.6, oblong: 0.7, triangle: 0.7 },
    proportionEffect: { addsHeight: 0.03, addsWidth: 0.08, coversForeheadPct: 0.15, lengthPastChin: 0.3 },
    harmony: { narrowFace: 0.5, wideFace: -0.2, longForehead: 0.1, shortForehead: 0, strongJaw: 0.1, weakChin: 0.2 },
    description: "Loose, tousled waves at medium-to-long length. The wave pattern adds width and breaks up straight vertical lines.",
    profile: {
      crownHeight: 0.04,
      sideVolume: 0.09,
      backLength: 0.35,
      bangDrop: 0.08,
      bangType: "none",
      lengthLevel: "chest",
      taperSides: false,
      textureDetail: "wavy",
    },
  },

  curlyNatural: {
    id: "curlyNatural",
    name: "Natural Curls",
    gender: "women",
    hairTypes: ["curly", "coily"],
    faceShapeAffinity: { oval: 0.8, heart: 0.7, diamond: 0.8, square: 0.7, round: 0.4, oblong: 0.7, triangle: 0.6 },
    proportionEffect: { addsHeight: 0.1, addsWidth: 0.15, coversForeheadPct: 0.3, lengthPastChin: 0.1 },
    harmony: { narrowFace: 0.7, wideFace: -0.5, longForehead: 0.2, shortForehead: 0.1, strongJaw: -0.1, weakChin: 0.1 },
    description: "Natural curly texture worn at its full volume. Adds significant width and some height — ideal for narrow or oblong faces.",
    profile: {
      crownHeight: 0.1,
      sideVolume: 0.15,
      backLength: 0.15,
      bangDrop: 0.15,
      bangType: "natural",
      lengthLevel: "shoulder",
      taperSides: false,
      textureDetail: "curly",
    },
  },

  afroWomen: {
    id: "afroWomen",
    name: "Afro",
    gender: "women",
    hairTypes: ["curly", "coily"],
    faceShapeAffinity: { oval: 0.8, heart: 0.7, diamond: 0.8, square: 0.7, round: 0.4, oblong: 0.7, triangle: 0.6 },
    proportionEffect: { addsHeight: 0.2, addsWidth: 0.2, coversForeheadPct: 0.3, lengthPastChin: 0 },
    harmony: { narrowFace: 0.7, wideFace: -0.5, longForehead: 0.2, shortForehead: 0.2, strongJaw: -0.2, weakChin: 0.1 },
    description: "Full, rounded natural texture. Adds major width and height simultaneously — best for narrow or angular faces.",
    profile: {
      crownHeight: 0.2,
      sideVolume: 0.2,
      backLength: 0.15,
      bangDrop: 0.1,
      bangType: "natural",
      lengthLevel: "above-ear",
      taperSides: false,
      textureDetail: "curly",
    },
  },

  highBun: {
    id: "highBun",
    name: "High Bun / Top Knot",
    gender: "women",
    hairTypes: ["straight", "wavy", "curly", "coily"],
    faceShapeAffinity: { oval: 0.9, heart: 0.6, diamond: 0.7, square: 0.6, round: 0.7, oblong: 0.3, triangle: 0.5 },
    proportionEffect: { addsHeight: 0.25, addsWidth: -0.02, coversForeheadPct: 0, lengthPastChin: 0 },
    harmony: { narrowFace: -0.3, wideFace: 0.5, longForehead: -0.6, shortForehead: 0.7, strongJaw: 0.3, weakChin: -0.3 },
    description: "Hair gathered into a bun at the crown. Fully exposes the face and adds height — elongates round or wide faces.",
    profile: {
      crownHeight: 0.25,
      sideVolume: 0.01,
      backLength: 0.02,
      bangDrop: 0,
      bangType: "none",
      lengthLevel: "pulled-up",
      taperSides: false,
      textureDetail: "minimal",
    },
  },

  lowBun: {
    id: "lowBun",
    name: "Low Bun / Chignon",
    gender: "women",
    hairTypes: ["straight", "wavy", "curly", "coily"],
    faceShapeAffinity: { oval: 0.9, heart: 0.7, diamond: 0.7, square: 0.7, round: 0.5, oblong: 0.6, triangle: 0.6 },
    proportionEffect: { addsHeight: 0.03, addsWidth: -0.02, coversForeheadPct: 0, lengthPastChin: 0 },
    harmony: { narrowFace: -0.2, wideFace: 0.2, longForehead: -0.4, shortForehead: 0.3, strongJaw: 0.3, weakChin: -0.2 },
    description: "Hair gathered at the nape. Clean, polished look that exposes the face fully without adding significant height.",
    profile: {
      crownHeight: 0.03,
      sideVolume: 0.01,
      backLength: 0.03,
      bangDrop: 0,
      bangType: "none",
      lengthLevel: "pulled-up",
      taperSides: false,
      textureDetail: "minimal",
    },
  },

  highPonytail: {
    id: "highPonytail",
    name: "High Ponytail",
    gender: "women",
    hairTypes: ["straight", "wavy", "curly", "coily"],
    faceShapeAffinity: { oval: 0.9, heart: 0.6, diamond: 0.7, square: 0.6, round: 0.7, oblong: 0.3, triangle: 0.5 },
    proportionEffect: { addsHeight: 0.15, addsWidth: -0.02, coversForeheadPct: 0, lengthPastChin: 0.2 },
    harmony: { narrowFace: -0.2, wideFace: 0.4, longForehead: -0.6, shortForehead: 0.6, strongJaw: 0.3, weakChin: -0.1 },
    description: "Ponytail at the crown. Lifts the face visually and adds some height — exposes forehead fully.",
    profile: {
      crownHeight: 0.15,
      sideVolume: 0.01,
      backLength: 0.2,
      bangDrop: 0,
      bangType: "none",
      lengthLevel: "pulled-up",
      taperSides: false,
      textureDetail: "minimal",
    },
  },

  lowPonytail: {
    id: "lowPonytail",
    name: "Low Ponytail",
    gender: "women",
    hairTypes: ["straight", "wavy", "curly", "coily"],
    faceShapeAffinity: { oval: 0.9, heart: 0.7, diamond: 0.7, square: 0.7, round: 0.5, oblong: 0.6, triangle: 0.6 },
    proportionEffect: { addsHeight: 0.02, addsWidth: -0.01, coversForeheadPct: 0, lengthPastChin: 0.15 },
    harmony: { narrowFace: -0.1, wideFace: 0.1, longForehead: -0.3, shortForehead: 0.2, strongJaw: 0.2, weakChin: 0 },
    description: "Ponytail at the nape. More subtle than a high ponytail — minimal face-shape correction.",
    profile: {
      crownHeight: 0.02,
      sideVolume: 0.01,
      backLength: 0.15,
      bangDrop: 0,
      bangType: "none",
      lengthLevel: "pulled-up",
      taperSides: false,
      textureDetail: "minimal",
    },
  },

  halfUp: {
    id: "halfUp",
    name: "Half-Up, Half-Down",
    gender: "women",
    hairTypes: ["straight", "wavy", "curly"],
    faceShapeAffinity: { oval: 0.9, heart: 0.8, diamond: 0.8, square: 0.7, round: 0.6, oblong: 0.6, triangle: 0.7 },
    proportionEffect: { addsHeight: 0.08, addsWidth: 0.04, coversForeheadPct: 0.1, lengthPastChin: 0.25 },
    harmony: { narrowFace: 0.1, wideFace: 0.2, longForehead: -0.2, shortForehead: 0.3, strongJaw: 0.1, weakChin: 0.1 },
    description: "Top half pulled back, bottom half down. Combines the height of an updo with the framing of loose hair.",
    profile: {
      crownHeight: 0.08,
      sideVolume: 0.05,
      backLength: 0.25,
      bangDrop: 0.05,
      bangType: "none",
      lengthLevel: "shoulder",
      taperSides: false,
      textureDetail: "moderate",
    },
  },

  sidePartLong: {
    id: "sidePartLong",
    name: "Side Part Long",
    gender: "women",
    hairTypes: ["straight", "wavy"],
    faceShapeAffinity: { oval: 0.9, heart: 0.8, diamond: 0.7, square: 0.7, round: 0.7, oblong: 0.6, triangle: 0.7 },
    proportionEffect: { addsHeight: 0.03, addsWidth: 0.05, coversForeheadPct: 0.3, lengthPastChin: 0.4 },
    harmony: { narrowFace: 0.2, wideFace: 0, longForehead: 0.3, shortForehead: -0.1, strongJaw: 0.1, weakChin: 0.2 },
    description: "Long hair with a deep side part. The asymmetry covers part of the forehead and adds diagonal movement.",
    profile: {
      crownHeight: 0.04,
      sideVolume: 0.05,
      backLength: 0.4,
      bangDrop: 0.15,
      bangType: "side-swept",
      lengthLevel: "chest",
      taperSides: false,
      textureDetail: "moderate",
    },
  },

  centerPartLong: {
    id: "centerPartLong",
    name: "Center Part Long",
    gender: "women",
    hairTypes: ["straight", "wavy"],
    faceShapeAffinity: { oval: 0.9, heart: 0.7, diamond: 0.7, square: 0.7, round: 0.6, oblong: 0.5, triangle: 0.7 },
    proportionEffect: { addsHeight: 0.02, addsWidth: 0.04, coversForeheadPct: 0.15, lengthPastChin: 0.45 },
    harmony: { narrowFace: 0.1, wideFace: 0.1, longForehead: 0.1, shortForehead: 0, strongJaw: 0.2, weakChin: 0.2 },
    description: "Long hair parted down the center. Creates a vertical line that narrows a wide face, with length that extends the lower face.",
    profile: {
      crownHeight: 0.02,
      sideVolume: 0.04,
      backLength: 0.4,
      bangDrop: 0.08,
      bangType: "none",
      lengthLevel: "chest",
      taperSides: false,
      textureDetail: "smooth",
    },
  },

  asymmetricBob: {
    id: "asymmetricBob",
    name: "Asymmetric Bob",
    gender: "women",
    hairTypes: ["straight", "wavy"],
    faceShapeAffinity: { oval: 0.8, heart: 0.8, diamond: 0.8, square: 0.7, round: 0.7, oblong: 0.7, triangle: 0.7 },
    proportionEffect: { addsHeight: 0.03, addsWidth: 0.05, coversForeheadPct: 0.2, lengthPastChin: 0 },
    harmony: { narrowFace: 0.2, wideFace: 0, longForehead: 0.1, shortForehead: 0, strongJaw: 0.2, weakChin: 0.2 },
    description: "Bob with one side longer than the other. Creates visual interest and can balance facial asymmetry.",
    profile: {
      crownHeight: 0.04,
      sideVolume: 0.05,
      backLength: 0.06,
      bangDrop: 0.12,
      bangType: "side-swept",
      lengthLevel: "chin",
      taperSides: false,
      textureDetail: "moderate",
    },
  },

  undercutPixie: {
    id: "undercutPixie",
    name: "Undercut Pixie",
    gender: "women",
    hairTypes: ["straight", "wavy", "curly"],
    faceShapeAffinity: { oval: 0.9, heart: 0.7, diamond: 0.8, square: 0.6, round: 0.6, oblong: 0.5, triangle: 0.5 },
    proportionEffect: { addsHeight: 0.1, addsWidth: -0.03, coversForeheadPct: 0.25, lengthPastChin: 0 },
    harmony: { narrowFace: -0.2, wideFace: 0.4, longForehead: 0.1, shortForehead: 0.3, strongJaw: 0.2, weakChin: 0 },
    description: "Pixie with shaved or very short sides and longer top. Creates strong vertical contrast like a men's undercut.",
    profile: {
      crownHeight: 0.1,
      sideVolume: 0.01,
      backLength: 0.03,
      bangDrop: 0.15,
      bangType: "side-swept",
      lengthLevel: "above-ear",
      taperSides: true,
      textureDetail: "moderate",
    },
  },

  texturedBob: {
    id: "texturedBob",
    name: "Textured Bob",
    gender: "women",
    hairTypes: ["wavy", "curly"],
    faceShapeAffinity: { oval: 0.9, heart: 0.8, diamond: 0.8, square: 0.7, round: 0.5, oblong: 0.8, triangle: 0.8 },
    proportionEffect: { addsHeight: 0.04, addsWidth: 0.09, coversForeheadPct: 0.15, lengthPastChin: 0 },
    harmony: { narrowFace: 0.5, wideFace: -0.3, longForehead: 0.1, shortForehead: 0, strongJaw: 0, weakChin: 0.3 },
    description: "Chin-length bob with waves or curls for texture. Adds substantial width at the jaw — good for narrow faces.",
    profile: {
      crownHeight: 0.05,
      sideVolume: 0.1,
      backLength: 0.08,
      bangDrop: 0.08,
      bangType: "none",
      lengthLevel: "chin",
      taperSides: false,
      textureDetail: "wavy",
    },
  },

  // ===================== UNISEX STYLES =====================
  buzzUnisex: {
    id: "buzzUnisex",
    name: "Buzz Cut",
    gender: "unisex",
    hairTypes: ["straight", "wavy", "curly", "coily"],
    faceShapeAffinity: { oval: 1.0, square: 0.9, diamond: 0.7, oblong: 0.4, round: 0.3, heart: 0.5, triangle: 0.6 },
    proportionEffect: { addsHeight: 0.02, addsWidth: 0, coversForeheadPct: 0, lengthPastChin: 0 },
    harmony: { narrowFace: -0.5, wideFace: 0.3, longForehead: -0.8, shortForehead: 0.8, strongJaw: 0.5, weakChin: -0.3 },
    description: "Closely clipped all over. Fully exposes face structure — requires balanced, strong features.",
    profile: {
      crownHeight: 0.02,
      sideVolume: 0.01,
      backLength: 0.02,
      bangDrop: 0,
      bangType: "none",
      lengthLevel: "above-ear",
      taperSides: true,
      textureDetail: "minimal",
    },
  },
};

export function getStylesForGender(gender) {
  return Object.values(database).filter(
    (s) => s.gender === gender || s.gender === "unisex"
  );
}

export function getStyleById(id) {
  return database[id] || null;
}

export function getAllStyles() {
  return Object.values(database);
}

export default database;
